services:
  anaconda:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./notebooks:/opt/notebooks
    restart: always
    ports:
      - "8888:8888"
    command:
      jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root
    stdin_open: true
